### ISSUE TITLE
I couldn't make the Socrates example work

### ISSUE THREAD

**Issue by hidenori-shinohara** [kenmcmil/ivy#1]
I was reading http://microsoft.github.io/ivy/proving.html and I tried to put together the proof that the Socrates is mortal by copying and pasting the code from the tutorial.

```
#lang ivy1.7    
                
type t        
              
relation man(X:t)              
relation mortal(X:t)        
                                     
axiom [mortality_of_man] {        
    property [prem] man(X)        
    #---------------         
    property mortal(X)                                
}                                                 
                                                  
individual socrates : t    
                           
axiom [soc_man] man(socrates)    
                                 
property mortal(socrates)    
proof {                      
    apply mortality_of_man with prem = soc_man    
}  
```

When I run `ivy_check diagnose=true proof.ivy` I get `proof.ivy: line 20: error: unknown symbol: prem` where Line 20 is `apply mortality_of_man with prem = soc_man`. It seems odd since I had already defined the property `prem` earlier.

I'm wondering how I can make this work. Thanks!

**Comment by asgeir386** [comment]
I saw the same issue before updating ivy, and after updating the issue went away

See http://microsoft.github.io/ivy/install.html

**Comment by hidenori-shinohara** [comment]
ah I see! Yes, it went away for me to. Thanks!
