### ISSUE TITLE
Requesting Pointers on Unbounded Model Checker

### ISSUE THREAD

**Issue by landonjefftaylor** [kenmcmil/ivy#10]
We are using the unbounded model checker feature of IVy to verify livelock issues in network-on-chip. We'd like to give a description of the ABC system, specifically what part(s) of ABC IVy's unbounded model checker uses.

Additionally, if anyone can provide references about IVy's unbounded model checker, we would greatly appreciate your insights.

**Comment by kenmcmil** [comment]
Ivy is currently only using the IC3-based model checker in ABC. 

Here's a citation for ABC (maybe not the best):

@inproceedings{DBLP:conf/cav/BraytonM10,
  author    = {Robert K. Brayton and
               Alan Mishchenko},
  title     = {{ABC:} An Academic Industrial-Strength Verification Tool},
  booktitle = {Computer Aided Verification, 22nd International Conference, {CAV}
               2010, Edinburgh, UK, July 15-19, 2010. Proceedings},
  pages     = {24--40},
  year      = {2010},
  crossref  = {DBLP:conf/cav/2010},
  timestamp = {Thu, 25 May 2017 00:39:07 +0200},
  biburl    = {http://dblp.org/rec/bib/conf/cav/BraytonM10},
  bibsource = {dblp computer science bibliography, http://dblp.org}
}

The best contact for ABC is the second author.
