### ISSUE TITLE
Options to view results

### ISSUE THREAD

**Issue by silverbucket** [kenmcmil/ivy#3]
I've been working on evaluating this as one tool for testing during QUIC development and I've had trouble getting to actually view results. Is using Tkinter the only option? Are there any screenshots or representations of what this will look like?

I am currently unable to use X11 Forwarding due to system issues and so, it seems I would need to have a local repo built along with one on the server, copy the results over and view them using TKinter on my local laptop. Which isn't great for automation and sharing with a development team.

Is there a way to view results using html/css etc.?

**Comment by hidenori-shinohara** [comment]
I run Ivy in a docker container, so Tkinter doesn't seem to work out of the box. I tried to set up X11 forwarding, but I couldn't get it to work, so I just use `trace=true`, and it has been working fine.

**Comment by silverbucket** [comment]
Hi @hidenori-shinohara and what type of results are provided with that parameter?

**Comment by hidenori-shinohara** [comment]
It shows the counterexample in texts.

```
searching for a small model... done
[
    @VALUE = 0                                                                           
    network.is_quorum(0) = true
    nset.member(0,0) = true
    nset.member(1,0) = true                      
    network.have_broadcast_vote(0,0) = true
    network.have_broadcast_vote(1,0) = false
    network.universe = 0
    node.have_voted(0,0) = true
```

You can just use the numbers as indices to visualize the counterexample.

* `network.is_quorum(0) = true` -> "Set 0 is a quorum"
* `nset.member(0,0) = true` -> "Node 0 is a member of Set 0"
* `network.have_broadcast_vote(1,0) = false` -> "Node 1 hasn't broadcast Statement 0"
* `network.universe = 0` -> "Set 0 is the universe"
* `node.have_voted(0,0) = true` -> "Node 0 has voted Statement 0"

**Comment by kenmcmil** [comment]
Right. Sorry I wasn't getting notifications on this repo. The trace=true option will produce a textual trace on stdout. The diagnose=true option causes the GUI to be started when a property fails.
