### ISSUE TITLE
Bounded Verification Feature

### ISSUE THREAD

**Issue by TonyZhangND** [kenmcmil/ivy#47]
Section 2.2 of the PLDI'16 paper describes a model checking functionality ion Ivy to rule out some protocol bugs before the inductive invariant search phase. 
However, I can't find any commands to do this bounded model checking. Is this feature still available?

**Comment by nano-o** [comment]
If I remember correctly, you have to add `attribute method=bmc[3]` (for a bound of 3 transitions) to the isolate you want to check.

**Comment by TonyZhangND** [comment]
Thank you, that worked!
