### ISSUE TITLE
Control `macro_finder` through the code itself

### ISSUE THREAD

**Issue by chandradeepdey** [kenmcmil/ivy#71]
In a project we are working on, for some isolates IVy does better with the `macro_finder` option, and in some other isolates it does worse with the option. So we were wondering if it would be possible to pass these hints to the solver in the code itself.

**Comment by chandradeepdey** [comment]
Tag @kenmcmil

**Comment by kenmcmil** [comment]
You can turn off the macro_finder option on a per-isolate basis by putting this declaration in the isolate:

        attribute macro_finder = false

**Comment by chandradeepdey** [comment]
Thank you.
